doc-warnings: false
test-warnings: false
strictness: veryhigh
max-line-length: 79
autodetect: yes
requirements:
    - requirements.txt
ignore-paths:
    - docs
    - migrations
    - flaskbb/configs
    - wsgi.py
pep8:
  full: true
  disable:
    - E711
    - E712
