language: python
sudo: false
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls"
  - "pip install -e ."
# command to run tests
script:
  - flaskbb translations compile
  - py.test --cov=flaskbb --cov-report=term-missing tests
after_success:
  - coveralls
